"""Apply reviewer revisions to the JRU paper."""

import docx
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

DOCX = r'C:\source\erisml-lib\docs\papers\paper4-variable-loss-aversion\Bond_2026_Variable_Loss_Aversion_JRU.docx'
doc = docx.Document(DOCX)

fixes = 0

for i, p in enumerate(doc.paragraphs):
    text = p.text.strip()
    if not text:
        continue

    for r in p.runs:
        rt = r.text
        changed = False

        # ── FIX 1: Tone down "no existing model" claims ──
        if 'no existing model predicts this variation from first principles' in rt:
            rt = rt.replace(
                'No existing model predicts this variation from first principles.',
                'To our knowledge, no existing model derives this variation from structural assumptions about the decision space.'
            )
            changed = True

        if 'no existing theory\u2014Nash, CPT, or Fehr\u2013Schmidt\u2014can generate without per-game' in rt:
            rt = rt.replace(
                'no existing theory\u2014Nash, CPT, or Fehr\u2013Schmidt\u2014can generate without per-game parameter fitting',
                'Nash equilibrium (which predicts poorly), CPT, and Fehr\u2013Schmidt all require per-game parameter fitting to generate'
            )
            changed = True

        # ── FIX 2: Fix heirloom inconsistency — remove "effective ≈ 12.5" ──
        if 'd \u2248 12.5, matching the upper range' in rt:
            rt = rt.replace(
                'd \u2248 12.5, matching the upper range of meta-analytic variation',
                'd = 7, yielding \u03bb = 2.65, within the meta-analytic range'
            )
            changed = True

        if '\u03bb = 3.53 for heirlooms' in rt:
            rt = rt.replace(
                '\u03bb = 3.53 for heirlooms (d \u2248 12.5, matching the upper range of meta-analytic variation)',
                '\u03bb = 2.65 for heirlooms (d = 7). Under the calibrated (non-isotropic) \u03a3, the effective \u03bb is higher due to the precision weighting of non-monetary dimensions'
            )
            changed = True

        # ── FIX 3: Qualify zero-parameter claim ──
        if 'zero free parameters from a covariance matrix calibrated' in rt:
            rt = rt.replace(
                'zero free parameters from a covariance matrix calibrated on ultimatum game data alone',
                'a single structural input (\u03a3) calibrated on ultimatum game data, with dimensional loadings assigned by qualitative assessment rather than fitted to loss-aversion data'
            )
            changed = True

        # ── FIX 4: Frame √d as special case ──
        if 'This function has no free parameters once the attribute space is specified' in rt:
            rt = rt.replace(
                'This function has no free parameters once the attribute space is specified.',
                'This is the isotropic special case of a more general formula (Proposition 1). Under the calibrated \u03a3, which is strongly anisotropic (\u03c3\u2081\u2081 = 25.0 for the monetary dimension vs. \u03c3_kk = 0.25 for non-monetary dimensions), the non-monetary dimensions carry 100\u00d7 higher precision weight, amplifying the geometric asymmetry beyond the \u221ad benchmark.'
            )
            changed = True

        # ── FIX 5: Tone down "absent from all existing models" ──
        if 'This prediction is absent from all existing models' in rt:
            rt = rt.replace(
                'This prediction is absent from all existing models',
                'To our knowledge, this prediction is not generated by existing behavioral models'
            )
            changed = True

        # ── FIX 6: Qualify "derives a number that is usually fitted" ──
        if 'it derives a number that is usually fitted' in rt:
            rt = rt.replace(
                'it derives a number that is usually fitted',
                'it derives a structural relationship (\u03bb as a function of d) where CPT uses a fitted constant'
            )
            changed = True

        if changed:
            r.text = rt
            fixes += 1

# ── FIX 7: Update Table 2 heirloom row ──
for table in doc.tables:
    for row in table.rows:
        cells = [c.text.strip() for c in row.cells]
        if 'Heirloom' in cells[0] if cells else False:
            if '12.5' in cells[1]:
                row.cells[1].paragraphs[0].runs[0].text = '7'
                row.cells[2].paragraphs[0].runs[0].text = '2.65'
                fixes += 1
                print(f'  Fixed Table: Heirloom row')
            if '3.53' in cells[2]:
                row.cells[2].paragraphs[0].runs[0].text = '2.65'
                fixes += 1

print(f'Total fixes: {fixes}')
doc.save(DOCX)
print(f'Saved: {DOCX}')
