/-
HohfeldV4.lean — machine-checked verification of the ErisML keystone correction
(erisml-lib commit ea7ee82, July 2026).

Claims verified against Mathlib:

  1. The two Hohfeldian operations — correlative swap `s` (O↔C, L↔N) and
     deontic negation `r²` (O↔L, C↔N) — are involutions and they COMMUTE.
  2. The subgroup of Perm(4) they generate is isomorphic to the Klein
     four-group V₄ (here `Multiplicative (ZMod 2 × ZMod 2)`), so it has
     exactly 4 elements.
  3. The quarter-turn `r` (O→C→L→N→O) is NOT in that subgroup: the dihedral
     D₄ is strictly more structure than the demonstrated operations generate.
  4. The ambient D₄ machinery is genuinely dihedral and non-abelian
     (r⁴ = 1, s² = 1, s·r·s = r⁻¹, r·s ≠ s·r) — so the posited extension is
     well-defined and testable, it just isn't what s and r² give you.

Positions are encoded 0 = Obligation, 1 = Claim, 2 = Liberty, 3 = No-claim,
matching src/erisml/ethics/hohfeld.py.
-/
import Mathlib

namespace Hohfeld

/-- Hohfeldian positions: 0 = Obligation, 1 = Claim, 2 = Liberty, 3 = No-claim. -/
abbrev Position : Type := Fin 4

/-- Correlative swap `s`: O↔C, L↔N (the agent↔patient swap the Bond Index tests). -/
def s : Equiv.Perm Position := Equiv.swap 0 1 * Equiv.swap 2 3

/-- The posited quarter-turn `r`: O→C→L→N→O (matches hohfeld.py's rotation). -/
def r : Equiv.Perm Position :=
  ⟨![1, 2, 3, 0], ![3, 0, 1, 2], by decide, by decide⟩

/-- Deontic negation `r²`: O↔L, C↔N. Defined as the square of the quarter-turn. -/
def r2 : Equiv.Perm Position := r * r

/-- Sanity: `r²` is exactly the pair of swaps O↔L, C↔N. -/
theorem r2_eq_swaps : r2 = Equiv.swap 0 2 * Equiv.swap 1 3 := by decide

/-! ### 1. The demonstrated operations are commuting involutions -/

theorem s_involution : s * s = 1 := by decide
theorem r2_involution : r2 * r2 = 1 := by decide
theorem s_r2_commute : s * r2 = r2 * s := by decide
theorem s_ne_one : s ≠ 1 := by decide
theorem r2_ne_one : r2 ≠ 1 := by decide
theorem s_ne_r2 : s ≠ r2 := by decide

/-! ### 2. They generate the Klein four-group V₄ -/

/-- The abstract Klein four-group, written multiplicatively. -/
abbrev K4 : Type := Multiplicative (ZMod 2 × ZMod 2)

/-- Parametrization of the generated subgroup by the Klein four-group. -/
def phi : K4 →* Equiv.Perm Position where
  toFun p := s ^ p.toAdd.1.val * r2 ^ p.toAdd.2.val
  map_one' := by decide
  map_mul' := by decide

theorem phi_injective : Function.Injective phi := by decide

theorem closure_eq_range :
    Subgroup.closure ({s, r2} : Set (Equiv.Perm Position)) = phi.range := by
  apply le_antisymm
  · rw [Subgroup.closure_le]
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl
    · exact ⟨Multiplicative.ofAdd (1, 0), by decide⟩
    · exact ⟨Multiplicative.ofAdd (0, 1), by decide⟩
  · rintro x ⟨p, rfl⟩
    have hs : s ∈ Subgroup.closure ({s, r2} : Set (Equiv.Perm Position)) :=
      Subgroup.subset_closure (by simp)
    have hr : r2 ∈ Subgroup.closure ({s, r2} : Set (Equiv.Perm Position)) :=
      Subgroup.subset_closure (by simp)
    exact mul_mem (pow_mem hs _) (pow_mem hr _)

/-- **The keystone theorem**: the subgroup generated by the two Hohfeldian
operations is isomorphic to the Klein four-group V₄. -/
noncomputable def closureMulEquivKleinFour :
    Subgroup.closure ({s, r2} : Set (Equiv.Perm Position)) ≃* K4 :=
  (MulEquiv.subgroupCongr closure_eq_range).trans
    (MonoidHom.ofInjective phi_injective).symm

/-- The generated subgroup has exactly 4 elements — order 4, not order 8. -/
theorem card_closure_eq_four :
    Nat.card (Subgroup.closure ({s, r2} : Set (Equiv.Perm Position))) = 4 := by
  rw [Nat.card_congr closureMulEquivKleinFour.toEquiv, Nat.card_eq_fintype_card]
  decide

/-! ### 3. The quarter-turn is NOT generated: D₄ ⊋ ⟨s, r²⟩ -/

theorem quarter_turn_not_generated :
    r ∉ Subgroup.closure ({s, r2} : Set (Equiv.Perm Position)) := by
  rw [closure_eq_range]
  rintro ⟨p, hp⟩
  exact absurd hp ((by decide : ∀ q : K4, phi q ≠ r) p)

/-! ### 4. The ambient machinery is genuinely dihedral (and non-abelian) -/

theorem r_pow_four : r ^ 4 = 1 := by decide
theorem r_pow_two_ne_one : r ^ 2 ≠ 1 := by decide
theorem dihedral_relation : s * r * s = r⁻¹ := by decide
theorem machinery_nonabelian : r * s ≠ s * r := by decide

/-- Summary statement, spelled out: the measured sector is abelian. -/
theorem measured_sector_abelian :
    ∀ x ∈ Subgroup.closure ({s, r2} : Set (Equiv.Perm Position)),
    ∀ y ∈ Subgroup.closure ({s, r2} : Set (Equiv.Perm Position)),
    x * y = y * x := by
  intro x hx y hy
  rw [closure_eq_range] at hx hy
  obtain ⟨p, rfl⟩ := hx
  obtain ⟨q, rfl⟩ := hy
  rw [← map_mul, ← map_mul, mul_comm p q]

end Hohfeld
